Repository nullworks/cathook, pull requests merged in 2020-10, with the labels that each got.

#1120 Remove /tmp/dumps chmod
  attach
  attach-gdb
  attach-libnamed.sh
  scripts/binarypackage/attach
Labels: p:high

#1119 AutoItem: replaces Achievement.cpp with autocraft and autorent system.
  data/menu/nullifiedcat/misc.xml
  data/menu/nullifiedcat/misc/autoequip.xml
  data/menu/nullifiedcat/misc/autoitem.xml
  include/hacks/Achievement.hpp
  include/hacks/hacklist.hpp
  include/reclasses/CTFInventoryManager.hpp
  src/hacks/Achievement.cpp
  src/hacks/AutoItem.cpp
  src/hacks/CMakeLists.txt
  src/reclasses/CTFInventoryManager.cpp
Labels: hacktoberfest-accepted

#1137 Fix truce and enable aimbot to aim at npcs
  data/menu/nullifiedcat/visuals/esp.xml
  include/core/netvars.hpp
  include/entitycache.hpp
  include/enums.hpp
  include/helpers.hpp
  include/itemtypes.hpp
  include/sdk/CGameRules.h
  src/PlayerTools.cpp
  src/core/netvars.cpp
  src/hacks/Aimbot.cpp
  src/hacks/ESP.cpp
  src/hacks/Misc.cpp
  src/helpers.cpp
  src/hooks/DispatchUserMessage.cpp
  src/itemtypes.cpp
Labels: p:medium
